import { bakedCatalog, type Catalog } from '../../../shared/catalog';
import { createChatView } from '../../app/src/state/chatView';
import {
  MemoryStorage,
  createChat,
  openPhone,
  reopen,
  settled,
  shutdown,
  startServer,
  type Phone,
  type Server,
} from './session-harness';

jest.setTimeout(60_000);
let server: Server;
beforeEach(async () => {
  server = await startServer();
});
afterEach(() => shutdown(server));

function openView(phone: Phone) {
  const errors: string[] = [];
  const store = createChatView(phone.archive, phone.session, error =>
    errors.push(error),
  );
  return { errors, state: () => store.getState() };
}

async function answer(phone: Phone, replyId: string): Promise<void> {
  server.providers.script(replyId).text('Answer').end();
  await settled(phone, replyId);
}

test('the view shows the open chat’s model, and a picked model is saved and sent with the next reply', async () => {
  const phone = openPhone(server);
  const chat = createChat(phone, 'kimi');
  const { errors, state } = openView(phone);
  expect(state().picker).toBe('kimi');

  state().setPicker('gpt-6.1-sol');
  expect(state().picker).toBe('gpt-6.1-sol');
  expect(reopen(phone.storage).chat(chat.id).picker).toBe('gpt-6.1-sol');

  state().send('Question');
  const reply = state().messages[1];
  await answer(phone, reply.id);
  expect(phone.archive.message(reply.id)).toMatchObject({
    picker: 'gpt-6.1-sol',
    actualModel: 'gpt-6.1-sol',
  });
  expect(server.providers.generations).toMatchObject([
    { model: 'gpt-6.1-sol', input: { picker: 'gpt-6.1-sol' } },
  ]);
  expect(server.providers.selections).toBe(0);
  expect(errors).toEqual([]);
});

test('a new chat starts on the open chat’s model, keeps its own choice, and each chat shows its own model when reopened', async () => {
  const phone = openPhone(server);
  const a = createChat(phone, 'kimi');
  const { errors, state } = openView(phone);
  state().setPicker('gpt-6.1-sol');
  state().send('In chat A');
  await answer(phone, state().messages[1].id);

  state().newChat();
  const b = state().chatId;
  expect(b).not.toBe(a.id);
  expect(state().picker).toBe('gpt-6.1-sol');

  state().setPicker('gpt-6-astra');
  expect(state().picker).toBe('gpt-6-astra');
  state().send('In chat B');
  await answer(phone, state().messages[1].id);

  state().openChat(a.id);
  expect(state()).toMatchObject({ chatId: a.id, picker: 'gpt-6.1-sol' });
  state().openChat(b);
  expect(state()).toMatchObject({ chatId: b, picker: 'gpt-6-astra' });

  const relaunched = openView(openPhone(server, phone.storage.snapshot()));
  expect(relaunched.state()).toMatchObject({
    chatId: b,
    picker: 'gpt-6-astra',
  });
  relaunched.state().openChat(a.id);
  expect(relaunched.state().picker).toBe('gpt-6.1-sol');
  expect(server.providers.generations.map(item => item.model)).toEqual([
    'gpt-6.1-sol',
    'gpt-6-astra',
  ]);
  expect(errors).toEqual([]);
});

test('a fresh install opens its first chat on DeepSeek, and a chat saved on Auto shows Auto until a model is picked', () => {
  const fresh = openPhone(server);
  const first = openView(fresh);
  expect(first.state().picker).toBe('deepseek');
  expect(reopen(fresh.storage).chat(first.state().chatId).picker).toBe(
    'deepseek',
  );

  const phone = openPhone(server);
  const chat = createChat(phone, 'auto');
  const { errors, state } = openView(phone);
  expect(state()).toMatchObject({ chatId: chat.id, picker: 'auto' });
  state().setPicker('kimi');
  expect(state().picker).toBe('kimi');
  expect(reopen(phone.storage).chat(chat.id).picker).toBe('kimi');
  expect(errors).toEqual([]);
});

test('the first message on a fresh install is generated by the model its pill shows', async () => {
  const phone = openPhone(server);
  const { errors, state } = openView(phone);
  const shown = state().picker;
  expect(shown).toBe('deepseek');

  state().send('First question');
  const reply = state().messages[1];
  await answer(phone, reply.id);
  expect(phone.archive.message(reply.id)).toMatchObject({
    picker: shown,
    actualModel: shown,
  });
  expect(server.providers.generations).toMatchObject([
    { model: shown, input: { picker: shown } },
  ]);
  expect(server.providers.selections).toBe(0);
  expect(errors).toEqual([]);
});

const [deepseek, , sol, astra] = bakedCatalog.models;

test('a cold start shows the cached catalog and opens on its first model without a request', () => {
  const cached: Catalog = { auto: false, models: [sol, deepseek] };
  const storage = new MemoryStorage();
  storage.set('catalog/v1', JSON.stringify(cached));
  const phone = openPhone(server, storage);
  phone.network.online = false;
  const { errors, state } = openView(phone);
  expect(state()).toMatchObject({ catalog: cached, picker: 'gpt-6.1-sol' });
  expect(phone.network.requests).toEqual([]);
  expect(errors).toEqual([]);
});

test('a fetched catalog replaces the cache, and a failed fetch or an unreadable body keeps it', async () => {
  const served: Catalog = { auto: false, models: [astra] };
  server.services.catalog = served;
  const phone = openPhone(server);
  const { errors, state } = openView(phone);
  expect(state().catalog).toEqual(bakedCatalog);

  state().receiveCatalog(
    await phone.transport.models(new AbortController().signal),
  );
  expect(state().catalog).toEqual(served);
  expect(reopen(phone.storage).catalog()).toEqual(served);

  phone.network.online = false;
  await expect(
    phone.transport.models(new AbortController().signal),
  ).rejects.toThrow('Network request failed');
  state().receiveCatalog('{"auto":');
  state().receiveCatalog('{"auto":true,"models":[]}');
  expect(state().catalog).toEqual(served);
  expect(reopen(phone.storage).catalog()).toEqual(served);
  expect(errors).toEqual([]);
});
