// Lines the motion-lines rule must match and must not match.
const mustMatch = [
  ['B01', 'export const motion = {'],
  ['B02', '  fast: 150,'],
  ['B03', '  base: 200,'],
  ['B04', '  send: 250,'],
  ['B05', '  easeOut: Easing.bezier(0.23, 1, 0.32, 1),'],
  ['B06', '  easeInOut: Easing.bezier(0.77, 0, 0.175, 1),'],
  ['B07', "import { Easing } from 'react-native-reanimated';"],
  [
    'B08',
    '        entering={justSent ? FadeInDown.duration(motion.send).easing(motion.easeOut) : undefined}',
  ],
  ['B09', '  0: { opacity: 0, transform: [{ translateY: 24 }] },'],
  ['B10', '<LayoutAnimationConfig skipEntering={!justSent}>'],
  ['B11', 'const reduceMotion = useReducedMotion();'],
  ['B12', '  useReducedMotion,'],
  ['B13', "import { useReducedMotion } from 'react-native-reanimated';"],
  [
    'B14',
    '        entering={reduceMotion ? FadeIn.duration(motion.fast) : sendRise}',
  ],
  [
    'B15',
    'const fadeOnly = FadeIn.duration(motion.fast).reduceMotion(ReduceMotion.Never);',
  ],
  ['B16', '  reduceMotion: ReduceMotion.System,'],
  ['B17', 'const rm = ReduceMotion.System;'],
  [
    'B18',
    '          entering={FadeIn.delay(motion.fast).duration(motion.base)}',
  ],
  [
    'B19',
    "          streamingAnimation={message.status === 'streaming' && !reduceMotion}",
  ],
  ['B20', "          streamingAnimation={message.status === 'streaming'}"],
  ['B21', 'const buttonIn = new Keyframe({'],
  ['B22', '  0: { opacity: 0, transform: [{ scale: 0.9 }] },'],
  [
    'B23',
    '  100: { opacity: 1, transform: [{ scale: 1 }], easing: motion.easeOut },',
  ],
  ['B24', '}).duration(motion.fast);'],
  ['B25', 'const buttonOut = FadeOut.duration(120).easing(motion.easeOut);'],
  ['B26', '      exiting={reduceMotion ? FadeOut.duration(120) : buttonOut}'],
  [
    'B27',
    'const enter = new Keyframe({ 0: { opacity: 0, transform: [{ scale: 0.9 }] }, 100: { opacity: 1, transform: [{ scale: 1 }] } });',
  ],
  ['B28', '      easing: motion.easeInOut,'],
  ['B29', '      duration: motion.base,'],
  ['B30', '      duration: reduceMotion ? 0 : motion.base,'],
  ['B31', '      easing: Easing.bezier(0.77, 0, 0.175, 1),'],
  [
    'B32',
    '    opacity: withTiming(hasAttachments ? 1 : 0, { duration: motion.fast }),',
  ],
  ['B43', '      duration: 220,'],
  [
    'B33',
    '  if (reduceMotion) return <Text style={styles.label}>{text}</Text>;',
  ],
  [
    'B34',
    '    transform: [{ scale: withTiming(pressed.value ? 0.97 : 1, { duration: 120 }) }],',
  ],
  [
    'B35',
    '      style={({ pressed }) => [styles.closeButton, pressed && { transform: [{ scale: 0.97 }] }]}',
  ],
  [
    'B36',
    '      onPressIn={() => (scale.value = withTiming(0.97, { duration: motion.fast }))}',
  ],
  ['B37', 'withSpring(1, { duration: 400, dampingRatio: 1 })'],
  ['B38', 'const settle = { duration: 400, dampingRatio: 1 };'],
  ['B39', '  dampingRatio: 0.8,'],
  ['B40', '  withSpring,'],
  ['B41', '  ReduceMotion,'],
  ['B42', '  Keyframe,'],
  ['H01', 'const rise = FadeInDown.duration(motion.send);'],
  ['H02', '        entering={rise}'],
  ['H03', '  const scale = useSharedValue(1);'],
  [
    'H04',
    '    scale.value = withTiming(pressed ? 0.97 : 1, { duration: motion.fast });',
  ],
  [
    'H05',
    '  const style = useAnimatedStyle(() => ({ opacity: opacity.value }));',
  ],
  ['H07', '  const enabled = await AccessibilityInfo.isReduceMotionEnabled();'],
  [
    'H08',
    "  AccessibilityInfo.addEventListener('reduceMotionChanged', setReduceMotion);",
  ],
  ['H11', '<Animated.View layout={LinearTransition.duration(motion.base)}>'],
  ['H12', '    transitionDuration: motion.base,'],
  [
    'H13',
    'const sweep = withRepeat(withTiming(1, { duration: 1500, easing: Easing.linear }), -1);',
  ],
  [
    'H15',
    '  if (reduceMotion) { opacity.value = withTiming(1, { duration: motion.fast }); return; }',
  ],
  ['H17', '  damping: 20,'],
  ['H18', 'const springConfig = { dampingRatio: 1, duration: motion.base };'],
  ['H21', '    runOnJS(setVisible)(false);'],
  ['H22', '  const offset = useScrollViewOffset(scrollRef);'],
  ['H23', '    opacity: interpolate(progress.value, [0, 1], [0, 1]),'],
  ['H24', '      exiting={buttonOut}'],
];

const mustNotMatch = [
  ['C01', 'const SEARCH_TIMEOUT_MS = 10000;'],
  ['C02', 'export const draftPauseMs = 500;'],
  ['C03', 'const dayMs = 24 * 60 * 60 * 1000;'],
  ['C04', '    this.checkpointMs = options.checkpointMs ?? 1000;'],
  ['C05', '    this.retryMaxMs = options.retryMaxMs ?? 30_000;'],
  ['C06', '      this.retryBaseMs * 2 ** (failures - 1),'],
  ['C07', '  const delay = Math.min(1000 * 2 ** attempts, 4000);'],
  ['C08', '    }, delay);'],
  [
    'C09',
    '  const timer = setTimeout(() => storeDraft(chatId, text), draftPauseMs);',
  ],
  [
    'C10',
    '  const timeout = setTimeout(() => controller.abort(), SEARCH_TIMEOUT_MS);',
  ],
  ['C11', '  const [now, setNow] = useState(Date.now);'],
  [
    'C12',
    'export function openArchive(now: () => number = Date.now): ChatArchive {',
  ],
  ['C13', '    flushHandle = requestAnimationFrame(flushDeltas);'],
  ['C14', '    cancelAnimationFrame(flushHandle);'],
  ['C15', '    scheduleFrame: callback => requestAnimationFrame(callback),'],
  ['C16', '  { scale: 0.75, quality: 60 },'],
  ['C17', '        Math.round(full.width * scale),'],
  ['C18', '    const measured = Math.round(event.nativeEvent.layout.height);'],
  ['C19', '        onLayout={onComposerLayout}'],
  ['C20', '  type LayoutChangeEvent,'],
  ['C21', '    send: data => socket.send(data),'],
  ['C22', '  send: (text: string, attachments?: Attachment[]) => SendResult;'],
  ['C23', '    opacity: 0.2,'],
  [
    'C24',
    '  // Default threshold is too tight for fast streaming and permanently stops the follow.',
  ],
  ['C25', '    const timer = setTimeout(refresh, midnight.getTime() - now);'],
  ['C26', "    console.log('[ws] reconnecting in', delay, 'ms');"],
  ['C27', '  checkpointMs?: number;'],
  ['C28', '  /** Dim base color of the glyphs. */'],
  ['C29', 'const pollDuration = 500;'],
  ['C30', 'const timeout_ms = 5;'],
  ['C31', 'const RETRY_MS = 500;'],
  ['C33', '<Row layout={styles.row} />'],
  ['C34', 'const timeoutDuration = 30_000;'],
  ['C35', 'const REQUEST_TIMEOUT_MS = 15_000;'],
  ['C36', 'const RECONNECT_DURATION = 4000;'],
  ['C37', '  const delayMs = retryDelay(attempt);'],
  ['C38', '  await new Promise(resolve => setTimeout(resolve, 250));'],
  ['C39', '  const elapsed = Date.now() - startedAt;'],
  ['C40', '    signal: AbortSignal.timeout(10_000),'],
  ['C41', '  debounceMs: 300,'],
  ['C42', '  interval: 5000,'],
  ['C43', '  fast: true,'],
  ['C44', '  base: 16,'],
  ['C45', '    width: 140,'],
  ['C46', "  1: { fontSize: 24, lineHeight: 30, fontWeight: '700' },"],
  ['C47', 'const pollDelay = 500;'],
  ['HC1', 'const FETCH_TIMEOUT_MS = 20_000;'],
  ['HC2', 'const pollIntervalMs = 2000;'],
  ['HC5', 'const DURATION_LIMIT_MS = 60_000;'],
  ['HC7', 'const transitionTo = (state: AttemptState) => state;'],
  ['HC8', 'const easingFactor = 0.5;'],
  ['HC9', '  timeoutMs: 1500,'],
  ['HC10', 'const sendDelay = 300;'],
];

module.exports = { mustMatch, mustNotMatch };
